[profile.default]
src = "contracts"
out = "artifacts"
libs = ["lib"]
solc = "0.8.24"

legacy_assertions = false
[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 500
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_run_limit = 5000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
